-- MySQL Script generated by MySQL Workbench
-- mar. 14 avril 2020 01:47:51 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema coureurs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coureurs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coureurs` ;
USE `coureurs` ;

-- -----------------------------------------------------
-- Table `coureurs`.`coureur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coureurs`.`coureur` (
  `co_id` INT NOT NULL,
  `co_nom` VARCHAR(45) NULL,
  `co_prenom` VARCHAR(45) NULL,
  `co_naissance` DATE NULL,
  `co_sexe` VARCHAR(45) NULL,
  PRIMARY KEY (`co_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coureurs`.`epreuve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coureurs`.`epreuve` (
  `ep_id` INT NOT NULL,
  `ep_nom` VARCHAR(45) NULL,
  `ep_distance` VARCHAR(45) NULL,
  PRIMARY KEY (`ep_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coureurs`.`inscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coureurs`.`inscription` (
  `in_dossart` INT NOT NULL,
  `in_categorie` VARCHAR(45) NULL,
  `in_date` VARCHAR(45) NULL,
  `coureur_co_id` INT NOT NULL,
  `epreuve_ep_id` INT NOT NULL,
  PRIMARY KEY (`in_dossart`, `coureur_co_id`, `epreuve_ep_id`),
 
  CONSTRAINT `fk_inscription_coureur`
    FOREIGN KEY (`coureur_co_id`)
    REFERENCES `coureurs`.`coureur` (`co_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscription_epreuve1`
    FOREIGN KEY (`epreuve_ep_id`)
    REFERENCES `coureurs`.`epreuve` (`ep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
