USE SIRENE
CREATE TABLE Niveau_93 (
N_700 VARCHAR(5) COMMENT "",
N_220 VARCHAR(3) COMMENT "",
N_60 VARCHAR(2) COMMENT "",
N_31 VARCHAR(1) COMMENT "",
N_17 VARCHAR(1) COMMENT "");

USE SIRENE ;
DROP TABLE Section_93 ;


