-- MySQL Script generated by MySQL Workbench
-- dim. 12 avril 2020 01:13:50 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET latin1 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`communes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`communes` (
  `idcommunes` INT NOT NULL,
  `nom_communes` VARCHAR(45) NULL,
  `pop_communes` VARCHAR(45) NULL,
  PRIMARY KEY (`idcommunes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`propriétaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`propriétaire` (
  `idpropriétaire` INT NOT NULL,
  `propriétairecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idpropriétaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`parcelles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`parcelles` (
  `idparcelles` INT NOT NULL,
  `superficie_par` DOUBLE NULL,
  `nom_par` VARCHAR(45) NULL,
  `communes_idcommunes` INT NOT NULL,
  `propriétaire_idpropriétaire` INT NOT NULL,
  PRIMARY KEY (`idparcelles`, `communes_idcommunes`, `propriétaire_idpropriétaire`),
   CONSTRAINT `fk_parcelles_communes`
    FOREIGN KEY (`communes_idcommunes`)
    REFERENCES `blog`.`communes` (`idcommunes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parcelles_propriétaire1`
    FOREIGN KEY (`propriétaire_idpropriétaire`)
    REFERENCES `blog`.`propriétaire` (`idpropriétaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`routes` (
  `idroutes` INT NOT NULL,
  `longueur_routes` VARCHAR(45) NULL,
  PRIMARY KEY (`idroutes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`communes_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`communes_routes` (
  `communes_idcommunes` INT NOT NULL,
  `routes_idroutes` INT NOT NULL,
  PRIMARY KEY (`communes_idcommunes`, `routes_idroutes`),
    CONSTRAINT `fk_communes_has_routes_communes1`
    FOREIGN KEY (`communes_idcommunes`)
    REFERENCES `blog`.`communes` (`idcommunes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_communes_has_routes_routes1`
    FOREIGN KEY (`routes_idroutes`)
    REFERENCES `blog`.`routes` (`idroutes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
